[project]
account_tier = "free"
database_major_version = 15
[api]
enabled = true
max_body_size = 20
default_query_only = true
[db]
major_version = 15
[realtime]
enabled = true
max_bytes_per_second = 0
[auth]
enabled = true
