drop extension if exists "pg_net";

create sequence "public"."inventory_inventory_id_seq";

create sequence "public"."inventory_movements_movement_id_seq";

create sequence "public"."promotions_promo_id_seq";

create sequence "public"."suppliers_supplier_id_seq";

create sequence "public"."team_members_id_seq";

create sequence "public"."web_logs_log_id_seq";

alter table "public"."sales" drop constraint "sales_customer_id_fkey";

alter table "public"."sales" drop constraint "sales_product_id_fkey";

alter table "public"."sales" drop constraint "sales_pkey";

alter table "public"."customers" drop constraint "customers_pkey";

alter table "public"."products" drop constraint "products_pkey";

drop index if exists "public"."sales_pkey";

drop index if exists "public"."customers_pkey";

drop index if exists "public"."products_pkey";


  create table "public"."Exercise 1B" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."Exercise 1B" enable row level security;


  create table "public"."inventory" (
    "inventory_id" integer not null default nextval('public.inventory_inventory_id_seq'::regclass),
    "product_id" integer not null,
    "location" character varying(20) not null,
    "quantity_available" integer not null default 0,
    "reorder_point" integer not null default 20,
    "last_updated" timestamp without time zone not null
      );


alter table "public"."inventory" enable row level security;


  create table "public"."inventory_movements" (
    "movement_id" integer not null default nextval('public.inventory_movements_movement_id_seq'::regclass),
    "product_id" integer not null,
    "location" character varying(20) not null,
    "movement_type" character varying(15) not null,
    "quantity" integer not null,
    "timestamp" timestamp without time zone not null,
    "reference" character varying(50)
      );


alter table "public"."inventory_movements" enable row level security;


  create table "public"."promotions" (
    "promo_id" integer not null default nextval('public.promotions_promo_id_seq'::regclass),
    "promo_name" character varying(200) not null,
    "product_id" integer,
    "category" character varying(50),
    "discount_percent" integer not null,
    "start_date" date not null,
    "end_date" date not null,
    "channel" character varying(10)
      );


alter table "public"."promotions" enable row level security;


  create table "public"."sales_import" (
    "sale_id" text,
    "invoice_id" text,
    "sale_date" text,
    "customer_id" text,
    "product_id" text,
    "quantity" text,
    "unit_price" text,
    "total_price" text,
    "channel" text,
    "store_location" text,
    "payment_method" text
      );


alter table "public"."sales_import" enable row level security;


  create table "public"."suppliers" (
    "supplier_id" integer not null default nextval('public.suppliers_supplier_id_seq'::regclass),
    "supplier_name" character varying(200) not null,
    "contact_email" character varying(200),
    "country" character varying(5) not null,
    "payment_terms_days" integer not null default 30,
    "lead_time_days" integer not null default 14,
    "reliability_score" numeric(3,2)
      );


alter table "public"."suppliers" enable row level security;


  create table "public"."team_members" (
    "id" integer not null default nextval('public.team_members_id_seq'::regclass),
    "name" character varying(100) not null,
    "role" character varying(100),
    "week" integer default 0,
    "joined_at" timestamp without time zone default now()
      );


alter table "public"."team_members" enable row level security;


  create table "public"."web_logs" (
    "log_id" integer not null default nextval('public.web_logs_log_id_seq'::regclass),
    "session_id" character varying(40) not null,
    "customer_id" integer,
    "visit_date" timestamp without time zone not null,
    "page_viewed" character varying(100) not null,
    "device_type" character varying(10) not null,
    "duration_seconds" integer not null default 0,
    "source" character varying(50),
    "country" character varying(5) default 'EE'::character varying
      );


alter table "public"."web_logs" enable row level security;

alter table "public"."customers" drop column "id";

alter table "public"."customers" drop column "name";

alter table "public"."customers" add column "birth_year" integer;

alter table "public"."customers" add column "customer_id" integer not null;

alter table "public"."customers" add column "first_name" character varying(50) not null;

alter table "public"."customers" add column "last_name" character varying(50) not null;

alter table "public"."customers" add column "loyalty_tier" character varying(10);

alter table "public"."customers" add column "phone" character varying(20);

alter table "public"."customers" add column "registration_date" date not null;

alter table "public"."customers" alter column "city" drop not null;

alter table "public"."customers" alter column "city" set data type character varying(50) using "city"::character varying(50);

alter table "public"."customers" alter column "email" drop not null;

alter table "public"."customers" alter column "email" set data type character varying(200) using "email"::character varying(200);

alter table "public"."customers" enable row level security;

alter table "public"."products" drop column "id";

alter table "public"."products" drop column "name";

alter table "public"."products" drop column "price";

alter table "public"."products" add column "cost_price" numeric(10,2) not null;

alter table "public"."products" add column "created_at" date not null;

alter table "public"."products" add column "eco_certified" boolean;

alter table "public"."products" add column "product_id" integer not null;

alter table "public"."products" add column "product_name" character varying(200) not null;

alter table "public"."products" add column "retail_price" numeric(10,2) not null;

alter table "public"."products" add column "subcategory" character varying(50) not null;

alter table "public"."products" add column "supplier" character varying(200);

alter table "public"."products" alter column "category" set data type character varying(50) using "category"::character varying(50);

alter table "public"."products" enable row level security;

alter table "public"."sales" drop column "id";

alter table "public"."sales" add column "channel" text;

alter table "public"."sales" add column "invoice_id" text;

alter table "public"."sales" add column "payment_method" text;

alter table "public"."sales" add column "sale_id" integer;

alter table "public"."sales" add column "store_location" text;

alter table "public"."sales" add column "total_price" numeric;

alter table "public"."sales" add column "unit_price" numeric;

alter table "public"."sales" alter column "quantity" drop not null;

alter table "public"."sales" alter column "sale_date" drop default;

alter table "public"."sales" enable row level security;

alter sequence "public"."inventory_inventory_id_seq" owned by "public"."inventory"."inventory_id";

alter sequence "public"."inventory_movements_movement_id_seq" owned by "public"."inventory_movements"."movement_id";

alter sequence "public"."promotions_promo_id_seq" owned by "public"."promotions"."promo_id";

alter sequence "public"."suppliers_supplier_id_seq" owned by "public"."suppliers"."supplier_id";

alter sequence "public"."team_members_id_seq" owned by "public"."team_members"."id";

alter sequence "public"."web_logs_log_id_seq" owned by "public"."web_logs"."log_id";

drop sequence if exists "public"."customers_id_seq";

drop sequence if exists "public"."products_id_seq";

drop sequence if exists "public"."sales_id_seq";

CREATE UNIQUE INDEX "Exercise 1B_pkey" ON public."Exercise 1B" USING btree (id);

CREATE INDEX idx_inventory_location ON public.inventory USING btree (location);

CREATE INDEX idx_inventory_movements_product ON public.inventory_movements USING btree (product_id);

CREATE INDEX idx_inventory_movements_timestamp ON public.inventory_movements USING btree ("timestamp");

CREATE INDEX idx_inventory_movements_type ON public.inventory_movements USING btree (movement_type);

CREATE INDEX idx_inventory_product ON public.inventory USING btree (product_id);

CREATE INDEX idx_promotions_category ON public.promotions USING btree (category);

CREATE INDEX idx_promotions_dates ON public.promotions USING btree (start_date, end_date);

CREATE INDEX idx_promotions_product ON public.promotions USING btree (product_id);

CREATE INDEX idx_web_logs_customer ON public.web_logs USING btree (customer_id);

CREATE INDEX idx_web_logs_date ON public.web_logs USING btree (visit_date);

CREATE INDEX idx_web_logs_session ON public.web_logs USING btree (session_id);

CREATE UNIQUE INDEX inventory_movements_pkey ON public.inventory_movements USING btree (movement_id);

CREATE UNIQUE INDEX inventory_pkey ON public.inventory USING btree (inventory_id);

CREATE UNIQUE INDEX inventory_product_id_location_key ON public.inventory USING btree (product_id, location);

CREATE UNIQUE INDEX promotions_pkey ON public.promotions USING btree (promo_id);

CREATE UNIQUE INDEX suppliers_pkey ON public.suppliers USING btree (supplier_id);

CREATE UNIQUE INDEX team_members_pkey ON public.team_members USING btree (id);

CREATE UNIQUE INDEX web_logs_pkey ON public.web_logs USING btree (log_id);

CREATE UNIQUE INDEX customers_pkey ON public.customers USING btree (customer_id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (product_id);

alter table "public"."Exercise 1B" add constraint "Exercise 1B_pkey" PRIMARY KEY using index "Exercise 1B_pkey";

alter table "public"."inventory" add constraint "inventory_pkey" PRIMARY KEY using index "inventory_pkey";

alter table "public"."inventory_movements" add constraint "inventory_movements_pkey" PRIMARY KEY using index "inventory_movements_pkey";

alter table "public"."promotions" add constraint "promotions_pkey" PRIMARY KEY using index "promotions_pkey";

alter table "public"."suppliers" add constraint "suppliers_pkey" PRIMARY KEY using index "suppliers_pkey";

alter table "public"."team_members" add constraint "team_members_pkey" PRIMARY KEY using index "team_members_pkey";

alter table "public"."web_logs" add constraint "web_logs_pkey" PRIMARY KEY using index "web_logs_pkey";

alter table "public"."customers" add constraint "customers_pkey" PRIMARY KEY using index "customers_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."customers" add constraint "customers_birth_year_check" CHECK (((birth_year >= 1940) AND (birth_year <= 2010))) not valid;

alter table "public"."customers" validate constraint "customers_birth_year_check";

alter table "public"."inventory" add constraint "inventory_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) not valid;

alter table "public"."inventory" validate constraint "inventory_product_id_fkey";

alter table "public"."inventory" add constraint "inventory_product_id_location_key" UNIQUE using index "inventory_product_id_location_key";

alter table "public"."inventory_movements" add constraint "inventory_movements_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) not valid;

alter table "public"."inventory_movements" validate constraint "inventory_movements_product_id_fkey";

alter table "public"."promotions" add constraint "promotions_check" CHECK ((end_date >= start_date)) not valid;

alter table "public"."promotions" validate constraint "promotions_check";

alter table "public"."promotions" add constraint "promotions_discount_percent_check" CHECK (((discount_percent >= 1) AND (discount_percent <= 100))) not valid;

alter table "public"."promotions" validate constraint "promotions_discount_percent_check";

alter table "public"."promotions" add constraint "promotions_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) not valid;

alter table "public"."promotions" validate constraint "promotions_product_id_fkey";

alter table "public"."suppliers" add constraint "suppliers_reliability_score_check" CHECK (((reliability_score >= (0)::numeric) AND (reliability_score <= (1)::numeric))) not valid;

alter table "public"."suppliers" validate constraint "suppliers_reliability_score_check";

alter table "public"."web_logs" add constraint "web_logs_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id) not valid;

alter table "public"."web_logs" validate constraint "web_logs_customer_id_fkey";

grant delete on table "public"."Exercise 1B" to "anon";

grant insert on table "public"."Exercise 1B" to "anon";

grant references on table "public"."Exercise 1B" to "anon";

grant select on table "public"."Exercise 1B" to "anon";

grant trigger on table "public"."Exercise 1B" to "anon";

grant truncate on table "public"."Exercise 1B" to "anon";

grant update on table "public"."Exercise 1B" to "anon";

grant delete on table "public"."Exercise 1B" to "authenticated";

grant insert on table "public"."Exercise 1B" to "authenticated";

grant references on table "public"."Exercise 1B" to "authenticated";

grant select on table "public"."Exercise 1B" to "authenticated";

grant trigger on table "public"."Exercise 1B" to "authenticated";

grant truncate on table "public"."Exercise 1B" to "authenticated";

grant update on table "public"."Exercise 1B" to "authenticated";

grant delete on table "public"."Exercise 1B" to "service_role";

grant insert on table "public"."Exercise 1B" to "service_role";

grant references on table "public"."Exercise 1B" to "service_role";

grant select on table "public"."Exercise 1B" to "service_role";

grant trigger on table "public"."Exercise 1B" to "service_role";

grant truncate on table "public"."Exercise 1B" to "service_role";

grant update on table "public"."Exercise 1B" to "service_role";

grant delete on table "public"."customers" to "anon";

grant insert on table "public"."customers" to "anon";

grant select on table "public"."customers" to "anon";

grant update on table "public"."customers" to "anon";

grant delete on table "public"."customers" to "authenticated";

grant insert on table "public"."customers" to "authenticated";

grant select on table "public"."customers" to "authenticated";

grant update on table "public"."customers" to "authenticated";

grant delete on table "public"."customers" to "service_role";

grant insert on table "public"."customers" to "service_role";

grant select on table "public"."customers" to "service_role";

grant update on table "public"."customers" to "service_role";

grant delete on table "public"."inventory" to "anon";

grant insert on table "public"."inventory" to "anon";

grant references on table "public"."inventory" to "anon";

grant select on table "public"."inventory" to "anon";

grant trigger on table "public"."inventory" to "anon";

grant truncate on table "public"."inventory" to "anon";

grant update on table "public"."inventory" to "anon";

grant delete on table "public"."inventory" to "authenticated";

grant insert on table "public"."inventory" to "authenticated";

grant references on table "public"."inventory" to "authenticated";

grant select on table "public"."inventory" to "authenticated";

grant trigger on table "public"."inventory" to "authenticated";

grant truncate on table "public"."inventory" to "authenticated";

grant update on table "public"."inventory" to "authenticated";

grant delete on table "public"."inventory" to "service_role";

grant insert on table "public"."inventory" to "service_role";

grant references on table "public"."inventory" to "service_role";

grant select on table "public"."inventory" to "service_role";

grant trigger on table "public"."inventory" to "service_role";

grant truncate on table "public"."inventory" to "service_role";

grant update on table "public"."inventory" to "service_role";

grant delete on table "public"."inventory_movements" to "anon";

grant insert on table "public"."inventory_movements" to "anon";

grant references on table "public"."inventory_movements" to "anon";

grant select on table "public"."inventory_movements" to "anon";

grant trigger on table "public"."inventory_movements" to "anon";

grant truncate on table "public"."inventory_movements" to "anon";

grant update on table "public"."inventory_movements" to "anon";

grant delete on table "public"."inventory_movements" to "authenticated";

grant insert on table "public"."inventory_movements" to "authenticated";

grant references on table "public"."inventory_movements" to "authenticated";

grant select on table "public"."inventory_movements" to "authenticated";

grant trigger on table "public"."inventory_movements" to "authenticated";

grant truncate on table "public"."inventory_movements" to "authenticated";

grant update on table "public"."inventory_movements" to "authenticated";

grant delete on table "public"."inventory_movements" to "service_role";

grant insert on table "public"."inventory_movements" to "service_role";

grant references on table "public"."inventory_movements" to "service_role";

grant select on table "public"."inventory_movements" to "service_role";

grant trigger on table "public"."inventory_movements" to "service_role";

grant truncate on table "public"."inventory_movements" to "service_role";

grant update on table "public"."inventory_movements" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."promotions" to "anon";

grant insert on table "public"."promotions" to "anon";

grant references on table "public"."promotions" to "anon";

grant select on table "public"."promotions" to "anon";

grant trigger on table "public"."promotions" to "anon";

grant truncate on table "public"."promotions" to "anon";

grant update on table "public"."promotions" to "anon";

grant delete on table "public"."promotions" to "authenticated";

grant insert on table "public"."promotions" to "authenticated";

grant references on table "public"."promotions" to "authenticated";

grant select on table "public"."promotions" to "authenticated";

grant trigger on table "public"."promotions" to "authenticated";

grant truncate on table "public"."promotions" to "authenticated";

grant update on table "public"."promotions" to "authenticated";

grant delete on table "public"."promotions" to "service_role";

grant insert on table "public"."promotions" to "service_role";

grant references on table "public"."promotions" to "service_role";

grant select on table "public"."promotions" to "service_role";

grant trigger on table "public"."promotions" to "service_role";

grant truncate on table "public"."promotions" to "service_role";

grant update on table "public"."promotions" to "service_role";

grant delete on table "public"."sales" to "anon";

grant insert on table "public"."sales" to "anon";

grant select on table "public"."sales" to "anon";

grant update on table "public"."sales" to "anon";

grant delete on table "public"."sales" to "authenticated";

grant insert on table "public"."sales" to "authenticated";

grant select on table "public"."sales" to "authenticated";

grant update on table "public"."sales" to "authenticated";

grant delete on table "public"."sales" to "service_role";

grant insert on table "public"."sales" to "service_role";

grant select on table "public"."sales" to "service_role";

grant update on table "public"."sales" to "service_role";

grant delete on table "public"."sales_import" to "anon";

grant insert on table "public"."sales_import" to "anon";

grant references on table "public"."sales_import" to "anon";

grant select on table "public"."sales_import" to "anon";

grant trigger on table "public"."sales_import" to "anon";

grant truncate on table "public"."sales_import" to "anon";

grant update on table "public"."sales_import" to "anon";

grant delete on table "public"."sales_import" to "authenticated";

grant insert on table "public"."sales_import" to "authenticated";

grant references on table "public"."sales_import" to "authenticated";

grant select on table "public"."sales_import" to "authenticated";

grant trigger on table "public"."sales_import" to "authenticated";

grant truncate on table "public"."sales_import" to "authenticated";

grant update on table "public"."sales_import" to "authenticated";

grant delete on table "public"."sales_import" to "service_role";

grant insert on table "public"."sales_import" to "service_role";

grant references on table "public"."sales_import" to "service_role";

grant select on table "public"."sales_import" to "service_role";

grant trigger on table "public"."sales_import" to "service_role";

grant truncate on table "public"."sales_import" to "service_role";

grant update on table "public"."sales_import" to "service_role";

grant delete on table "public"."suppliers" to "anon";

grant insert on table "public"."suppliers" to "anon";

grant references on table "public"."suppliers" to "anon";

grant select on table "public"."suppliers" to "anon";

grant trigger on table "public"."suppliers" to "anon";

grant truncate on table "public"."suppliers" to "anon";

grant update on table "public"."suppliers" to "anon";

grant delete on table "public"."suppliers" to "authenticated";

grant insert on table "public"."suppliers" to "authenticated";

grant references on table "public"."suppliers" to "authenticated";

grant select on table "public"."suppliers" to "authenticated";

grant trigger on table "public"."suppliers" to "authenticated";

grant truncate on table "public"."suppliers" to "authenticated";

grant update on table "public"."suppliers" to "authenticated";

grant delete on table "public"."suppliers" to "service_role";

grant insert on table "public"."suppliers" to "service_role";

grant references on table "public"."suppliers" to "service_role";

grant select on table "public"."suppliers" to "service_role";

grant trigger on table "public"."suppliers" to "service_role";

grant truncate on table "public"."suppliers" to "service_role";

grant update on table "public"."suppliers" to "service_role";

grant delete on table "public"."team_members" to "anon";

grant insert on table "public"."team_members" to "anon";

grant references on table "public"."team_members" to "anon";

grant select on table "public"."team_members" to "anon";

grant trigger on table "public"."team_members" to "anon";

grant truncate on table "public"."team_members" to "anon";

grant update on table "public"."team_members" to "anon";

grant delete on table "public"."team_members" to "authenticated";

grant insert on table "public"."team_members" to "authenticated";

grant references on table "public"."team_members" to "authenticated";

grant select on table "public"."team_members" to "authenticated";

grant trigger on table "public"."team_members" to "authenticated";

grant truncate on table "public"."team_members" to "authenticated";

grant update on table "public"."team_members" to "authenticated";

grant delete on table "public"."team_members" to "service_role";

grant insert on table "public"."team_members" to "service_role";

grant references on table "public"."team_members" to "service_role";

grant select on table "public"."team_members" to "service_role";

grant trigger on table "public"."team_members" to "service_role";

grant truncate on table "public"."team_members" to "service_role";

grant update on table "public"."team_members" to "service_role";

grant delete on table "public"."web_logs" to "anon";

grant insert on table "public"."web_logs" to "anon";

grant references on table "public"."web_logs" to "anon";

grant select on table "public"."web_logs" to "anon";

grant trigger on table "public"."web_logs" to "anon";

grant truncate on table "public"."web_logs" to "anon";

grant update on table "public"."web_logs" to "anon";

grant delete on table "public"."web_logs" to "authenticated";

grant insert on table "public"."web_logs" to "authenticated";

grant references on table "public"."web_logs" to "authenticated";

grant select on table "public"."web_logs" to "authenticated";

grant trigger on table "public"."web_logs" to "authenticated";

grant truncate on table "public"."web_logs" to "authenticated";

grant update on table "public"."web_logs" to "authenticated";

grant delete on table "public"."web_logs" to "service_role";

grant insert on table "public"."web_logs" to "service_role";

grant references on table "public"."web_logs" to "service_role";

grant select on table "public"."web_logs" to "service_role";

grant trigger on table "public"."web_logs" to "service_role";

grant truncate on table "public"."web_logs" to "service_role";

grant update on table "public"."web_logs" to "service_role";


